// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// ArtifactPVC represents the pvc created by the pipelinerun
// for artifacts temporary storage
ArtifactPVC :: {
	Name:                  string
	PersistentVolumeClaim: null | PersistentVolumeClaim @go(,*github.com/tektoncd/pipeline/vendor/corev1.PersistentVolumeClaim)
}
