// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// BucketConfigName is the name of the configmap containing all
// customizations for the storage bucket.
BucketConfigName :: "config-artifact-bucket"

// BucketLocationKey is the name of the configmap entry that specifies
// loction of the bucket.
BucketLocationKey :: "location"

// BucketServiceAccountSecretName is the name of the configmap entry that specifies
// the name of the secret that will provide the servie account with bucket access.
// This secret must  have a key called serviceaccount that will have a value with
// the service account with access to the bucket
BucketServiceAccountSecretName :: "bucket.service.account.secret.name"

// BucketServiceAccountSecretKey is the name of the configmap entry that specifies
// the secret key that will have a value with the service account json with access
// to the bucket
BucketServiceAccountSecretKey :: "bucket.service.account.secret.key"

// PipelineResourceTypeGit indicates that this source is a GitHub repo.
ArtifactStorageBucketType :: "bucket"

// PipelineResourceTypeStorage indicates that this source is a storage blob resource.
ArtifactStoragePVCType :: "pvc"

// ArtifactBucket contains the Storage bucket configuration defined in the
// Bucket config map.
ArtifactBucket :: {
	Name:     string
	Location: string
	Secrets: [...SecretParam] @go(,[]SecretParam)
}
