// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// GCSArtifactType defines a type of GCS resource.
GCSArtifactType :: string // enumGCSArtifactType

enumGCSArtifactType ::
	GCSArchive |
	GCSZipArchive |
	GCSTarGzArchive |
	GCSManifest

// GCSZipArchive indicates that the resource should be fetched and
// extracted as a .zip file.
//
// Deprecated: Use GCSZipArchive instead.
GCSArchive :: GCSArtifactType & "Archive"

// GCSZipArchive indicates that the resource should be fetched and
// extracted as a .zip file.
GCSZipArchive :: GCSArtifactType & "ZipArchive"

// GCSTarGzArchive indicates that the resource should be fetched and
// extracted as a .tar.gz file.
GCSTarGzArchive :: GCSArtifactType & "TarGzArchive"

// GCSManifest indicates that resource should be fetched using a
// manifest-based protocol which enables incremental source upload.
GCSManifest :: GCSArtifactType & "Manifest"

BuildGCSResource :: {
	Name:         string
	Type:         PipelineResourceType
	Location:     string
	ArtifactType: GCSArtifactType
}
