// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// ClusterTask is a Task with a cluster scope. ClusterTasks are used to
// represent Tasks that should be publicly addressable from any namespace in the
// cluster.
ClusterTask :: {
	TypeMeta

	// +optional
	metadata?: ObjectMeta @go(ObjectMeta,github.com/tektoncd/pipeline/vendor/metav1.ObjectMeta)

	// Spec holds the desired state of the Task from the client
	// +optional
	spec?: TaskSpec @go(Spec)
}

// ClusterTaskList contains a list of ClusterTask
ClusterTaskList :: {
	TypeMeta

	// +optional
	metadata?: ListMeta @go(ListMeta,github.com/tektoncd/pipeline/vendor/metav1.ListMeta)
	items: [...ClusterTask] @go(Items,[]ClusterTask)
}
