// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// Node represents a Task in a pipeline.
Node :: {
	// Task represent the PipelineTask in Pipeline
	Task: PipelineTask

	// Prev represent all the Previous task Nodes for the current Task
	Prev: [...null | Node] @go(,[]*Node)

	// Next represent all the Next task Nodes for the current Task
	Next: [...null | Node] @go(,[]*Node)
}

// DAG represents the Pipeline DAG
DAG :: {
	//Nodes represent map of PipelineTask name to Node in Pipeline DAG
	Nodes: {<_>: null | Node} @go(,map[string]*Node)
}
