// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// ImageResource defines an endpoint where artifacts can be stored, such as images.
ImageResource :: {
	name:           string               @go(Name)
	type:           PipelineResourceType @go(Type)
	url:            string               @go(URL)
	digest:         string               @go(Digest)
	OutputImageDir: string
}
