// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

// PullRequestResource is an endpoint from which to get data which is required
// by a Build/Task for context.
PullRequestResource :: {
	name: string               @go(Name)
	type: PipelineResourceType @go(Type)

	// GitHub URL pointing to the pull request.
	// Example: https://github.com/owner/repo/pulls/1
	url: string @go(URL)

	// Secrets holds a struct to indicate a field name and corresponding secret name to populate it.
	secrets: [...SecretParam] @go(Secrets,[]SecretParam)
}
