// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1

package v1alpha1

PipelineResourceStorageType :: string

// PipelineResourceTypeGCS indicates that resource source is a GCS blob/directory.
PipelineResourceTypeGCS ::      PipelineResourceType & "gcs"
PipelineResourceTypeBuildGCS :: PipelineResourceType & "build-gcs"

// PipelineResourceInterface interface to be implemented by different PipelineResource types
PipelineStorageResourceInterface :: _
