apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: build-deploy-pipeline
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  resources:
    - name: source-repo
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-image
      taskRef:
        name: build-image-from-git-source
      params:
        - name: pathToContext
          value: /workspace/source
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: docker-image

    # This is a workaround because the digest is not updated yet by tekton.
    # See https://github.com/tektoncd/pipeline/issues/216 and https://github.com/tektoncd/catalog/pull/68
    - name: update-digest
      params:
        - name: pipelineTask
          value: build-image
      runAfter:
        - build-image
      taskRef:
        name: update-image-digests

    - name: deploy-image
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - update-digest
      params:
        - name: path
          value: /workspace/source/deployment.yaml
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: docker-image
