apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: image-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  type: image
  params:
    - name: url
      value: {{ .Values.image.name }}
