apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: pipeline-run-{{ .Values.global.ci.uid }}
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting ci/resources"
spec:
  serviceAccount: docker
  pipelineRef:
    name: build-deploy-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: repository-{{ .Values.global.ci.uid }}
    - name: docker-image
      resourceRef:
        name: image-{{ .Values.global.ci.uid }}
