apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  namespace: {{ .Values.global.ci.namespace }}
  name: build-image-from-git-source
  annotations:
    kapp.k14s.io/change-group: "ci/resources"
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToContext
        type: string
        description:
          The directory containing the default.nix file
        default: /workspace/source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: docker.io/lewo/n2k8s:latest
      command:
        - /entrypoint
      args:
        - --context
        - $(inputs.params.pathToContext)
        - --destination
        - $(outputs.resources.builtImage.url)
        - --image-manifest-filepath
        - /builder/home/image-outputs/builtImage/index.json
